using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.PlayerLoop;
using UnityEngine.SceneManagement;
using UnityEngine.Serialization;
using UnityEngine.UI;
using Random = UnityEngine.Random;

public class Enemy : MonoBehaviour
{
    private GameObject _alarmSign;
    private Collider2D _collider2D;
    private EnemyState _currentState;
    public Animator animator;
    public int animState;
    public readonly PatrolState PatrolState = new PatrolState();
    public readonly AttackState AttackState = new AttackState();
    public Transform pointA, pointB;
    public Transform targetPoint;
    public Slider healthBar;
    public float speed;
    public bool isTryOut;

    [Header("Base Setting")] 
    public float health;
    public bool isDead;
    public bool hasBomb;
    public bool isBoss;
    public bool isIdle;
    public bool isStatic;
    [Header("Attack Check")] 
    public float attackRate;
    // public float skillAttackRate;
    public float attackRange;
    private float _nextAttack = 0;
    
    [Header("Attack List")]
    public List<Transform> transforms = new List<Transform>();
    
    [Header("Coins & Cherry")]
    public GameObject coinPrefabs;
    public GameObject cherryPrefabs;
    public LayerMask coinLayer;
    public Transform underPoint;
    public int coinNumber;
    public virtual void Init()
    {
        //è¿™æ ·å†™çš„å¥½å¤„æ˜¯åœ¨å­ç±»ä¸­å¯ä»¥åœ¨åŸæœ‰çš„åŸºç¡€ä¸Šç»§ç»­å†™ä¸€äº›æœ¬èº«ä¸éœ€è¦çš„ä»£ç  æ¯”è¾ƒä¹‹æ–¹ä¾¿
        _collider2D = GetComponent<Collider2D>();
        animator = GetComponent<Animator>();
        _alarmSign = transform.GetChild(0).gameObject;
        //å¼€å§‹ç•Œé¢ä¸éœ€è¦è¿›å…¥ä¸‹é¢çš„æ–¹æ³•ï¼Œç›´æ¥è¿”å›
        if (SceneManager.GetActiveScene().name != "StartScene") return;
        isIdle = true;

    }

    public void Awake()
    {
        Init();
    }

    public virtual void Start()
    {
        //ä¸ä½¿ç”¨è¿™ä¸ªèµ‹å€¼æ–¹æ³• ä½¿ç”¨æ–°çš„è™šæ–¹æ³•
        // animator = GetComponent<Animator>();
        //æ¯ä¸ªenemyéƒ½æœ‰idleçŠ¶æ€ å’Œ æ”»å‡» çŠ¶æ€ å¯ä»¥éƒ½å†™ä¸€ä¸ªè¿™ä¸œè¥¿
        HealthBar();
        GameManager.Instance.IsEnemy(this);//åŠ å…¥enemyçš„list æ•Œäººéƒ½æŒ‚äº†è¯¥è„šæœ¬ å› æ­¤åœ¨è¿›å…¥ä¹‹åéƒ½ä¼šåŠ å…¥è¯¥listä¹‹ä¸­
        if(isIdle)
            return;
        TransitionToState(PatrolState);//when the game start, let the enemy go in patrol state
        if(isBoss)
            UIManager.instance.SetBossHealth(health);
    }

    // Update is called once per frame
    public virtual void Update()
    {
        UpdateHealth();
        if (isDead)
        {
            //æ­»äº¡åˆ¤æ–­
            animator.SetBool("dead",isDead);//è¢«ç‚¸å¼¹ç‚¸æ­»éœ€è¦åœ¨updateä¸­ä¸€ç›´åˆ¤æ–­
            Destroy(gameObject,0.2f);//captain
            return;
        }
        if(isIdle)
            return;
        if (isBoss)
            UIManager.instance.ReduceHealth(health);
        if (isTryOut)
            return;
        _currentState.onUpdate(this);//æ°¸è¿œéƒ½æ˜¯å½“å‰è„šæœ¬çš„æŒ‚è½½è€…æ‰§è¡Œ å·¡é€»
        animator.SetInteger("state",animState);//update enemy's current state frequently
    }

    private void HealthBar()
    {
        healthBar.maxValue = health;
    }

    private void UpdateHealth()
    {
        healthBar.value = health;
    }

    //çŠ¶æ€æœºçš„çŠ¶æ€è½¬å˜ ->é¦–å…ˆè·å¾—è¦è½¬å˜çš„çŠ¶æ€å€¼ ç„¶åè¿›å…¥è¯¥çŠ¶æ€
    public void TransitionToState(EnemyState state)
    {
        _currentState = state;
        _currentState.EnterState(this);
    }

    public void MoveToTarget()
    {
        transform.position = Vector2.MoveTowards(transform.position, targetPoint.position, speed * Time.deltaTime);
        FlipDirection();
    }

    public void BasicAttack()//å¯¹ç©å®¶çš„åŸºæœ¬æ”»å‡»
    {
        //è®¡æ—¶å™¨ç»™å®šæ”»å‡»é—´éš”å’ŒèŒƒå›´åˆ¤å®š
        if (!(Vector2.Distance(this.transform.position, targetPoint.transform.position) < attackRange)) return;
        if (!(Time.time > _nextAttack)) return;
        Debug.Log("basic attack");
        animator.SetTrigger("attack");
        _nextAttack = Time.time + attackRate;
    }
    public virtual void SkillAttack()//å¯¹ç‚¸å¼¹çš„æ”»å‡»
    {
        if (Vector2.Distance(transform.position,targetPoint.transform.position) < attackRange)
        {
            if (Time.time > _nextAttack)
            {
                Debug.Log("skill attack");
                animState = 2;
                animator.SetTrigger("skillAttack");
                _nextAttack = Time.time + attackRate;
            }
            // StartCoroutine()
        }
    }

    private void FlipDirection()
    {
        //on the right side of the enemy
        transform.rotation = Quaternion.Euler(0f, transform.position.x < targetPoint.position.x 
                            ? 180f : 0f, 0f);
    }

    public void SwitchPoint()
    {
        //è‡ªåŠ¨è®¡ç®—ç¦»å“ªä¸ªç‚¹è¿œ æ€»æ˜¯æœè¿œçš„ç‚¹èµ°
        var position = transform.position;
        //TODO ç›®æ ‡ä¼šå°†å±•ç¤ºç‰Œä½œä¸ºç›®æ ‡
        targetPoint = Mathf.Abs(pointA.position.x - position.x) 
                      > Mathf.Abs(pointB.position.x - position.x) ? pointA : pointB;
    }

    private void OnTriggerStay2D(Collider2D other)
    {
        //å¦‚æœå·²ç»åŒ…å«äº†è¯¥ç‰©ä½“ é‚£ä¹ˆå°±ä¸æ·»åŠ 
        if (!transforms.Contains(other.transform) && !hasBomb && !isDead && !GameManager.Instance.gameOver)
        {
            transforms.Add(other.transform);
        }
    }
    
    private void OnTriggerExit2D(Collider2D other)
    {
        transforms.Remove(other.transform);
    }

    private void OnTriggerEnter2D(Collider2D other)
    {
        if(!isDead && !GameManager.Instance.gameOver)
            StartCoroutine(OnAlarm());
    }

    IEnumerator OnAlarm()
    {
        _alarmSign.SetActive(true);
        yield return new WaitForSeconds(animator.GetComponent<Animator>().GetCurrentAnimatorClipInfo(0)[0].clip.length);
        _alarmSign.SetActive(false);
    }

    public void Explosion()//animation event
    {
        _collider2D.enabled = false; 
        
        Collider2D[] collider2Ds = Physics2D.OverlapCircleAll(underPoint.transform.position, 3f,coinLayer);
        
        foreach (var items in collider2Ds)
        {
            Vector3 pos = underPoint.transform.position - items.transform.position;
            // //è¿›è¿‡æµ‹è¯•çˆ†ç‚¸ä¹‹ååªæœ‰å·¦å³ä¸¤è¾¹çš„åŠ›ï¼Œç„¶è€ŒçœŸå®æƒ…å†µæ˜¯è¿˜éœ€è¦ä¸€ä¸ªå¾€ä¸Šçš„åŠ›ï¼ŒğŸ‘‡
            //ä¿®æ”¹ç‰ˆæœ¬
            items.GetComponent<Rigidbody2D>().AddForce((-pos + Vector3.up) * 2f,ForceMode2D.Impulse);
        }
    }
    
    private void Create()//animation event
    {
        for (int i = 0; i < coinNumber; i++)
        {
            float x = Random.Range(-1, 3);
            float y = Random.Range(1, 3);
            // Instantiate(coinPrefabs,new Vector3(transform.position.x+x,transform.position.y+y),transform.rotation);
            Instantiate(coinPrefabs,new Vector3(transform.position.x+x,transform.position.y+y),transform.rotation);
            GameManager.Instance.coins.Add(coinPrefabs);
        }

        foreach (var coin in GameManager.Instance.coins)
        {
            float randomForce = Random.Range(2, 5);
            coin.GetComponent<Rigidbody2D>().AddForce(Vector3.up * randomForce,ForceMode2D.Impulse);
        }

        var probability = Random.Range(1, 10);
        if(probability % 2 == 1)
            Instantiate(cherryPrefabs,new Vector3(transform.position.x+1,transform.position.y+1),transform.rotation);
    }

    
}
