using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CannonBomb : MonoBehaviour
{
    public float startTime;
    public float waitTime;
    public LayerMask groundCheck;
    private Collider2D _collider2D;
    private Animator _animator;
    private Rigidbody2D _rigidbody2D;
    void Start()
    {
        _animator = GetComponent<Animator>();
        _collider2D = GetComponent<Collider2D>();
        _rigidbody2D = GetComponent<Rigidbody2D>();
        startTime = Time.time;
    }

    // Update is called once per frame
    void Update()
    {
        if (_animator.GetCurrentAnimatorStateInfo(0).IsName("Idle"))
        {
            if (Time.time > startTime + waitTime)
            {
                _animator.Play("Explosion");
            }
        }
    }
    
    public void Explosion()
    {
        AudioManager.PlayAudio(AudioName.Explosion);
        _collider2D.enabled = false;

        Collider2D[] collider2Ds = Physics2D.OverlapCircleAll(transform.position, 3f, groundCheck);
        
        _rigidbody2D.gravityScale = 0;
        
        foreach (var items in collider2Ds)
        {
            Vector3 pos = transform.position - items.transform.position;
            // //è¿›è¿‡æµ‹è¯•çˆ†ç‚¸ä¹‹ååªæœ‰å·¦å³ä¸¤è¾¹çš„åŠ›ï¼Œç„¶è€ŒçœŸå®æƒ…å†µæ˜¯è¿˜éœ€è¦ä¸€ä¸ªå¾€ä¸Šçš„åŠ›ï¼ŒğŸ‘‡
            //ä¿®æ”¹ç‰ˆæœ¬
            items.GetComponent<Rigidbody2D>().AddForce((-pos + Vector3.up) * 5,ForceMode2D.Impulse);
            
            if (items.CompareTag("Player"))
            {
                items.GetComponent<IDamageable>().GetHit(3);
            }
            
            if (items.CompareTag("Enemy"))
            {
                items.GetComponent<IDamageable>().GetHit(3);
            }
        }
    }

    public void DestroyBomb()
    {
        Destroy(gameObject);
    }
}
