using System;
using System.Collections;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;
using UnityEngine.SceneManagement;

public class Bomb : MonoBehaviour
{
    private Animator _animator;
    private Collider2D _collider2D;
    private Rigidbody2D _rigidbody2D;
    public float startTime;
    public float waitTime;
    public float bombForce;
    
    [Header("Status Check")]
    public float radius;
    public LayerMask groundCheck;

    [Header("bomb")] public bool isBomb;
    
    // Start is called before the first frame update
    private void Start()
    {
        _animator = GetComponent<Animator>();
        _collider2D = GetComponent<Collider2D>();
        _rigidbody2D = GetComponent<Rigidbody2D>();
        startTime = Time.time;
    }

    // Update is called once per frame
    void Update()
    {
        //è§£å†³çˆ†ç‚¸é—®é¢˜
        if (!_animator.GetCurrentAnimatorStateInfo(0).IsName("bomb_off"))
        {
            if (Time.time > startTime + waitTime)
            {
                _animator.Play("bomb_explosion");
                
            }
        }
    }

    public void OnDrawGizmos()
    {
        Gizmos.DrawWireSphere(transform.position,radius);
    }

    public virtual void Explosion()//animation event çˆ†ç‚¸åŠ¨ç”»çš„ç¬¬ä¸€å¸§æ‰§è¡Œ
    {

        //bombçš„æ£€æµ‹ä¸­ä¼šå°†è‡ªå·±æ£€æµ‹è¿›å»ï¼Œçˆ†ç‚¸çš„æ—¶å€™ä¼šæœ‰ä¸€ä¸ªå‘ä¸Šçš„åŠ›ï¼Œå› ä¸ºè‡ªå·±ä¼šå»å’Œå‘¨å›´çš„ç¯å¢ƒç¢°æ’
        //è§£å†³æ–¹æ³•å°±æ˜¯åœ¨æ£€æµ‹ä¹‹å‰å°†è‡ªèº«çš„ç¢°æ’ä½“å…³é—­ï¼Œå¢åŠ ä¸€ä¸ªrigid2dçš„ï¼Œmassä¸º0çš„ä¸€ä¸ªç»„ä»¶
        _collider2D.enabled = false; 
        
        //è·å¾—æ£€æµ‹èŒƒå›´å†…æ‰€æœ‰çš„æœ‰ç¢°æ’ä½“çš„ä¸œè¥¿ï¼Œç„¶ååˆ¤æ–­å…¶æ–¹å‘æ˜¯åœ¨çˆ†ç‚¸çš„å·¦è¾¹è¿˜æ˜¯å³è¾¹ç­‰
        //åˆ¤æ–­æ–¹å‘çš„æ–¹æ³•å°±æ˜¯é€šè¿‡ç›¸å‡çš„æ–¹å¼å¯ä»¥å¾—å‡ºé‚£ä¸ªç¢°æ’ä½“å¯¹åº”çˆ†ç‚¸ç‚¹çš„ä¸€ä¸ªåæ ‡ï¼Œæ¯”å¦‚è¯´xyzä¸­å“ªä¸ªæ˜¯è´Ÿçš„å°±åœ¨å“ªé‡Œ
        //å®ç°ä¹‹åå°±è¦ç»™å…¶æ·»åŠ åŠ›ï¼Œä½†æ˜¯éœ€è¦æ³¨æ„çš„æ˜¯æ·»åŠ çš„åŠ›ä¸€å®šæ˜¯åæ–¹å‘æ¥æ·»åŠ çš„ï¼Œä¸ºäº†ç‰©ä½“ç‚¸å‡ºå»ï¼Œæ‰€ä»¥åŠ çš„åŠ›éœ€è¦åŠ è´Ÿå·
        Collider2D[] collider2Ds = Physics2D.OverlapCircleAll(transform.position, radius, groundCheck);
        
        _rigidbody2D.gravityScale = 0;
        
        foreach (var items in collider2Ds)
        {
            Vector3 pos = transform.position - items.transform.position;
            // //è¿›è¿‡æµ‹è¯•çˆ†ç‚¸ä¹‹ååªæœ‰å·¦å³ä¸¤è¾¹çš„åŠ›ï¼Œç„¶è€ŒçœŸå®æƒ…å†µæ˜¯è¿˜éœ€è¦ä¸€ä¸ªå¾€ä¸Šçš„åŠ›ï¼ŒğŸ‘‡
            //ä¿®æ”¹ç‰ˆæœ¬
            items.GetComponent<Rigidbody2D>().AddForce((-pos + Vector3.up) * bombForce,ForceMode2D.Impulse);

            //ç†„ç­çš„ç‚¸å¼¹ä¼šè¢«é‡æ–°ç‚¹ç‡ƒ å› æ­¤éœ€è¦åˆ¤æ–­æ˜¯å¦æ˜¯ç†„ç­çš„ç‚¸å¼¹ å¦‚æœæ˜¯ç‡ƒçƒ§çš„ç‚¸å¼¹åˆ™ä¼šå‘ç”Ÿé”™è¯¯
            if (items.CompareTag("Bomb") && items.GetComponent<Animator>().GetCurrentAnimatorStateInfo(0).IsName("bomb_off"))
            {
                isBomb = true;
                TurnOn();
            }
        }
    }

    public void DestroyBomb() //animation event
    {
        
        Destroy(gameObject);
    }

    public void BombSound()
    {
        AudioManager.PlayAudio(AudioName.Explosion);
    }
    
    public void TurnOff()
    {
        _animator.Play("bomb_off");
        gameObject.layer = LayerMask.NameToLayer("NPC");
        isBomb = false;
        //ç†„ç­ä¹‹åçš„ç‚¸å¼¹ä¸èƒ½å†ä½œä¸ºplayerçš„ç›®æ ‡
        //å› æ­¤éœ€è¦å°†å…¶çš„å›¾å±‚æ”¹æˆä¸å’Œå…¶å‘ç”Ÿå…³ç³»çš„å›¾å±‚ è¿™æ ·å°±ä¸ä¼šå†å»æ£€æµ‹äº†
    }

    private void TurnOn()
    {
        startTime = Time.time;//ç”±äºè®¡æ—¶å™¨å¼€ç‚¸å¼¹æ”¾ä¸‹æ—¶åˆ»å°±ä¼šå¯åŠ¨ï¼Œå› æ­¤å¦‚æœä¸é‡æ–°ä¸ºå…¶è®¡ç®—æ—¶é—´ï¼Œç‚¸å¼¹åˆ™ä¼šç¬é—´çˆ†ç‚¸ è¿™ä¸æ˜¯æƒ³è¦çš„æ•ˆæœ
        _animator.Play("bomb_on");
        gameObject.layer = LayerMask.NameToLayer("Bomb");
    }
    
}
